<a href="https://colab.research.google.com/github/himanshu91b/Google_Colab_ML_Models/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import os
#use to process image in real time 
import cv2
import numpy as np
#random number generator to use when shuffling the data
from sklearn.utils import shuffle
from keras import backend as K


from keras.utils import np_utils


from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
%matplotlib notebook
from sklearn import svm, metrics, datasets
from sklearn.utils import Bunch
from sklearn.model_selection import GridSearchCV, train_test_split

import skimage
from skimage.io import imread
from skimage.transform import resize
import matplotlib.cm as cm

print(__doc__)

from sklearn.metrics import plot_confusion_matrix


Using TensorFlow backend.


Automatically created module for IPython interactive environment


In [ ]:
img_rows= 128
img_cols= 128

#one color
num_channel=1
num_epoch=10

# Define the number of classes
num_classes = 3

#get full path
PATH = os.getcwd()
# Define data path
data_path = PATH + '/drive/My Drive/thesis/dataset/train'
data_dir_list = os.listdir(data_path)

img_data_list=[]

for dataset in data_dir_list:
	img_list=os.listdir(data_path+'/'+ dataset)
	print ('Loaded the images of dataset-'+'{}\n'.format(dataset))
	for img in img_list:
		input_img=cv2.imread(data_path + '/'+ dataset + '/'+ img )
		input_img=cv2.cvtColor(input_img, cv2.COLOR_BGR2GRAY)
		input_img_resize=cv2.resize(input_img,(128,128)).flatten()
		img_data_list.append(input_img_resize)
  
#input_shape=(128, 128, 1) for 128x128 RGB pictures in  data_format="channels_last"
img_data = np.array(img_data_list)
img_data = img_data.astype('float32')
img_data /= 255
print (img_data.shape)

Loaded the images of dataset-Leaf smut

Loaded the images of dataset-Brown spot

Loaded the images of dataset-Bacterial leaf blight

(627, 16384)


In [ ]:
num_of_samples = img_data.shape[0]
labels = np.ones((num_of_samples,),dtype='int64')

labels[0:403]=0
labels[404:606]=1
labels[607:1706]=2

# labels[606:]=3


In [ ]:
names = ['Brown spot','Leaf smut','Bacterial leaf blight']

# convert class labels to on-hot encoding
Y = np_utils.to_categorical(labels, num_classes)

#Shuffle the dataset
x,y = shuffle(img_data,Y, random_state=2)
x = img_data
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(x, labels, test_size=0.3, random_state=2, stratify=labels)

accuracies=[]
kVals = range(1, 30, 2)

for k in range(1, 30, 2):
	# train the k-Nearest Neighbor classifier with the current value of `k`
	knn = KNeighborsClassifier(n_neighbors = k)
	knn.fit(X_train,y_train)
 
	# evaluate the model and update the accuracies list
	score = knn.score(X_test, y_test)
	print("k=%d, accuracy=%.2f%%" % (k, score * 100))
	accuracies.append(score)
 
# find the value of k that has the largest accuracy
i = int(np.argmax(accuracies))
print("k=%d achieved highest accuracy of %.2f%% on validation data" % (kVals[i],
	accuracies[i] * 100))

k=1, accuracy=68.78%
k=3, accuracy=67.20%
k=5, accuracy=67.72%
k=7, accuracy=67.20%
k=9, accuracy=64.55%
k=11, accuracy=65.08%
k=13, accuracy=64.02%
k=15, accuracy=62.96%
k=17, accuracy=61.38%
k=19, accuracy=60.32%
k=21, accuracy=60.32%
k=23, accuracy=58.73%
k=25, accuracy=59.79%
k=27, accuracy=59.26%
k=29, accuracy=59.26%
k=1 achieved highest accuracy of 68.78% on validation data


In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
print("Classification report for - \n{}:\n{}\n".format(
    knn, metrics.classification_report(y_test, y_pred)))

Classification report for - 
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=29, p=2,
                     weights='uniform'):
              precision    recall  f1-score   support

           0       0.69      0.68      0.69       121
           1       0.41      0.47      0.44        62
           2       1.00      0.17      0.29         6

    accuracy                           0.59       189
   macro avg       0.70      0.44      0.47       189
weighted avg       0.61      0.59      0.59       189




In [ ]:
titles_options = [("Confusion matrix, without normalization", None),
                  ("Normalized confusion matrix", 'true')]
for title, normalize in titles_options:
    disp = plot_confusion_matrix(knn, X_test, y_test,
                                 
                                 cmap=plt.cm.Blues,
                                 normalize=normalize)
    disp.ax_.set_title(title)

    print(title)
    print(disp.confusion_matrix)

plt.show()

<IPython.core.display.Javascript object>

Confusion matrix, without normalization
[[82 39  0]
 [33 29  0]
 [ 3  2  1]]


<IPython.core.display.Javascript object>

Normalized confusion matrix
[[0.67768595 0.32231405 0.        ]
 [0.53225806 0.46774194 0.        ]
 [0.5        0.33333333 0.16666667]]
